package arraylistgui;


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArrayListGUI.java
 *
 * Created on Oct 29, 2011, 1:49:00 PM
 */

/**
 *
 * @author andrea
 */
public class ArrayListGUI extends javax.swing.JFrame {

    private TableModelPersonagem tableModelPersonagem;
    Controle c;
    Grupo auxiliar;
    /** Creates new form ArrayListGUI */
    public ArrayListGUI() {
        initComponents();
        //tableModelPersonagem = new TableModelPersonagem();
        c = new Controle(this);
        auxiliar = new Grupo();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AdicionaGrupo = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SalvarGrupo = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Apagar = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablegrupo = new javax.swing.JTable();
        nomegrupo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        RemovedoGrupo = new javax.swing.JButton();
        limpagrupo = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tablegrupopronto = new javax.swing.JTable();
        excluegrupo = new javax.swing.JButton();
        abregrupo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NomeJogador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomePersonagem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Raça = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Classe = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Habilidade = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Especialidade = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        LevelP = new javax.swing.JFormattedTextField();
        LevelH = new javax.swing.JFormattedTextField();
        Limpar = new javax.swing.JButton();
        Manhã = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Tarde = new javax.swing.JCheckBox();
        Noite = new javax.swing.JCheckBox();
        Noite1 = new javax.swing.JCheckBox();
        Manhã1 = new javax.swing.JCheckBox();
        Tarde1 = new javax.swing.JCheckBox();
        Manhã2 = new javax.swing.JCheckBox();
        Manhã3 = new javax.swing.JCheckBox();
        Manhã4 = new javax.swing.JCheckBox();
        Manhã5 = new javax.swing.JCheckBox();
        Manhã6 = new javax.swing.JCheckBox();
        Tarde2 = new javax.swing.JCheckBox();
        Tarde3 = new javax.swing.JCheckBox();
        Tarde4 = new javax.swing.JCheckBox();
        Tarde5 = new javax.swing.JCheckBox();
        Tarde6 = new javax.swing.JCheckBox();
        Noite2 = new javax.swing.JCheckBox();
        Noite3 = new javax.swing.JCheckBox();
        Noite4 = new javax.swing.JCheckBox();
        Noite5 = new javax.swing.JCheckBox();
        Noite6 = new javax.swing.JCheckBox();
        Todos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdicionaGrupo.setText("Adicionar ao Grupo");
        AdicionaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionaGrupoActionPerformed(evt);
            }
        });

        jLabel18.setText("Montar Grupo");

        jLabel19.setText("Personagens - Guild");

        SalvarGrupo.setText("Salvar Grupo");
        SalvarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarGrupoActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Jogador", "Nome do Personagem", "Level", "Classe", "Raça", "Habilidade", "LevelHab", "Especialidade", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(table);

        Apagar.setText("Apagar Personagem");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });

        tablegrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Jogador", "Nome do Personagem", "Level", "Classe", "Raça", "Habilidade", "LevelHab", "Especialidade", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablegrupo.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(tablegrupo);
        if (tablegrupo.getColumnModel().getColumnCount() > 0) {
            tablegrupo.getColumnModel().getColumn(1).setHeaderValue("Nome do Personagem");
            tablegrupo.getColumnModel().getColumn(2).setHeaderValue("Level");
            tablegrupo.getColumnModel().getColumn(3).setHeaderValue("Classe");
            tablegrupo.getColumnModel().getColumn(4).setHeaderValue("Raça");
            tablegrupo.getColumnModel().getColumn(5).setHeaderValue("Habilidade");
            tablegrupo.getColumnModel().getColumn(7).setHeaderValue("Especialidade");
            tablegrupo.getColumnModel().getColumn(8).setHeaderValue("Disponível");
        }

        jLabel17.setText("Nome Grupo");

        RemovedoGrupo.setText("Remover do Grupo");
        RemovedoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovedoGrupoActionPerformed(evt);
            }
        });

        limpagrupo.setText("Limpar Grupo");
        limpagrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpagrupoActionPerformed(evt);
            }
        });

        tablegrupopronto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Grupo", "Tamanho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablegrupopronto.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(tablegrupopronto);

        excluegrupo.setText("Excluir Grupo");
        excluegrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluegrupoActionPerformed(evt);
            }
        });

        abregrupo.setText("Abrir Grupo");
        abregrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abregrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane10)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(148, 148, 148)
                .addComponent(Apagar)
                .addGap(185, 185, 185))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalvarGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpagrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(AdicionaGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemovedoGrupo)
                        .addGap(176, 176, 176))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(excluegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(abregrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdicionaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemovedoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalvarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(limpagrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluegrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(458, Short.MAX_VALUE)
                    .addComponent(abregrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
        );

        jTabbedPane2.addTab("Guild", jPanel1);

        jLabel2.setText("Nome do Jogador:");

        NomeJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeJogadorActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Personagem:");

        jLabel4.setText("Level");

        NomePersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomePersonagemActionPerformed(evt);
            }
        });

        jLabel5.setText("Raça");

        Raça.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anão", "Draconato", "Elfo", "Gnomo", "Halfling", "Humano" }));

        jLabel6.setText("Classe");

        Classe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bárbaro", "Bruxo", "Clérigo", "Guerreiro", "Ladino", "Mago", "Paladino", "Ranger" }));

        jLabel7.setText("Habilidade");

        Habilidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adestrar Animais", "Acrobacia", "Furtividade", "HIstória", "Religião", "Percepção", "Blefe", "Identificar Magia" }));

        jLabel8.setText("Level");

        jLabel1.setText("Especialidade");

        Especialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agressor", "Controlador", "Líder", "Defensor" }));
        Especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Horários");

        Salvar.setText("Inserir");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        LevelP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LevelP.setText("1");

        LevelH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        LevelH.setText("1");
        LevelH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelHActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        Manhã.setText("Manhã");

        jLabel10.setText("Segunda");

        jLabel11.setText("Terça");

        jLabel12.setText("Quarta");

        jLabel13.setText("Quinta");

        jLabel14.setText("Sexta");

        jLabel15.setText("Sábado");

        jLabel16.setText("Domingo");

        Tarde.setText("Tarde");

        Noite.setText("Noite");
        Noite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoiteActionPerformed(evt);
            }
        });

        Noite1.setText("Noite");
        Noite1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite1ActionPerformed(evt);
            }
        });

        Manhã1.setText("Manhã");
        Manhã1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã1ActionPerformed(evt);
            }
        });

        Tarde1.setText("Tarde");

        Manhã2.setText("Manhã");
        Manhã2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã2ActionPerformed(evt);
            }
        });

        Manhã3.setText("Manhã");
        Manhã3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã3ActionPerformed(evt);
            }
        });

        Manhã4.setText("Manhã");
        Manhã4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã4ActionPerformed(evt);
            }
        });

        Manhã5.setText("Manhã");
        Manhã5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã5ActionPerformed(evt);
            }
        });

        Manhã6.setText("Manhã");
        Manhã6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manhã6ActionPerformed(evt);
            }
        });

        Tarde2.setText("Tarde");

        Tarde3.setText("Tarde");

        Tarde4.setText("Tarde");

        Tarde5.setText("Tarde");

        Tarde6.setText("Tarde");

        Noite2.setText("Noite");
        Noite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite2ActionPerformed(evt);
            }
        });

        Noite3.setText("Noite");
        Noite3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite3ActionPerformed(evt);
            }
        });

        Noite4.setText("Noite");
        Noite4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite4ActionPerformed(evt);
            }
        });

        Noite5.setText("Noite");
        Noite5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite5ActionPerformed(evt);
            }
        });

        Noite6.setText("Noite");
        Noite6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Noite6ActionPerformed(evt);
            }
        });

        Todos.setText("Todos");
        Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomePersonagem)
                            .addComponent(Habilidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Especialidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Raça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Classe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 648, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LevelP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LevelH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(13, 13, 13))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Manhã2)
                                    .addComponent(Manhã1)
                                    .addComponent(Manhã3)
                                    .addComponent(Manhã4)
                                    .addComponent(Manhã5)
                                    .addComponent(Manhã6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tarde1)
                                    .addComponent(Tarde2)
                                    .addComponent(Tarde3)
                                    .addComponent(Tarde4)
                                    .addComponent(Tarde5)
                                    .addComponent(Tarde6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Manhã)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tarde)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Noite)
                            .addComponent(Noite3)
                            .addComponent(Noite4)
                            .addComponent(Noite5)
                            .addComponent(Noite6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Noite1)
                                        .addGap(214, 214, 214))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Noite2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Salvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(Limpar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Todos)))
                .addGap(0, 231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(NomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LevelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Raça, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Habilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LevelH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Todos)))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Noite)
                    .addComponent(Tarde, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manhã))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manhã1)
                    .addComponent(Noite1)
                    .addComponent(Tarde1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Manhã2)
                    .addComponent(Tarde2)
                    .addComponent(Noite2)
                    .addComponent(Limpar)
                    .addComponent(Salvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manhã3)
                    .addComponent(Tarde3)
                    .addComponent(Noite3)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manhã4)
                    .addComponent(Tarde4)
                    .addComponent(Noite4)
                    .addComponent(jLabel14))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manhã5)
                    .addComponent(Tarde5)
                    .addComponent(Noite5)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manhã6)
                    .addComponent(Tarde6)
                    .addComponent(Noite6)
                    .addComponent(jLabel16))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Personagem", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomePersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomePersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomePersonagemActionPerformed

    private void EspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EspecialidadeActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        try {
            //teste se n selecionou nada
        
            if (!Manhã.isSelected()&&!Manhã1.isSelected()&&!Manhã2.isSelected()&&!Manhã3.isSelected()&&
                    !Manhã4.isSelected()&&!Manhã5.isSelected()&&!Manhã6.isSelected()&&!Tarde.isSelected()&&!Tarde1.isSelected()&&!Tarde2.isSelected()
                    &&!Tarde3.isSelected()&&!Tarde4.isSelected()&&!Tarde5.isSelected()&&!Tarde6.isSelected()&&!Noite.isSelected()&&!Noite1.isSelected()&&!Noite2.isSelected()&&!Noite3.isSelected()&&!Noite4.isSelected()&&!Noite5.isSelected()&&!Noite6.isSelected())
                return;
            Personagem p = new Personagem();
            p.setNomej(NomeJogador.getText().trim());
            p.setNomep(NomePersonagem.getText().trim());
            p.setLevelP(Integer.parseInt(LevelP.getText().trim()));
            p.setClasse((String)Classe.getSelectedItem());
            p.setRaça((String)Raça.getSelectedItem());
            p.setHabilidade((String)Habilidade.getSelectedItem());
            p.setEspecialidade((String)Especialidade.getSelectedItem());
            p.setLevelH(Integer.parseInt(LevelH.getText().trim()));
            p.setTrabalho(0,0,Manhã.isSelected());
            p.setTrabalho(1,0,Manhã1.isSelected());
            p.setTrabalho(2,0,Manhã2.isSelected());
            p.setTrabalho(3,0,Manhã3.isSelected());
            p.setTrabalho(4,0,Manhã4.isSelected());
            p.setTrabalho(5,0,Manhã5.isSelected());
            p.setTrabalho(6,0,Manhã6.isSelected());
            p.setTrabalho(0,1,Tarde.isSelected());
            p.setTrabalho(1,1,Tarde1.isSelected());
            p.setTrabalho(2,1,Tarde2.isSelected());
            p.setTrabalho(3,1,Tarde3.isSelected());
            p.setTrabalho(4,1,Tarde4.isSelected());
            p.setTrabalho(5,1,Tarde5.isSelected());
            p.setTrabalho(6,1,Tarde6.isSelected());
            p.setTrabalho(0,2,Noite.isSelected());
            p.setTrabalho(1,2,Noite1.isSelected());
            p.setTrabalho(2,2,Noite2.isSelected());
            p.setTrabalho(3,2,Noite3.isSelected());
            p.setTrabalho(4,2,Noite4.isSelected());
            p.setTrabalho(5,2,Noite5.isSelected());
            p.setTrabalho(6,2,Noite6.isSelected());
            String trabalho = p.vertrabalho();
            DefaultTableModel val = (DefaultTableModel)table.getModel();
            val.addRow(new String[]{p.nomej,p.nomep,Integer.toString(p.levelp),p.classe,p.raça,p.habilidade,Integer.toString(p.levelh),p.especialidade,trabalho});
            limpar();
            c.salvar(p);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dado(s) de entrada invalido(s)!");
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void LevelHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelHActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        //limparPersonagem();
        limpar();
    }//GEN-LAST:event_LimparActionPerformed

    private void NomeJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeJogadorActionPerformed

    private void AdicionaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionaGrupoActionPerformed
        int i = table.getSelectedRow();
        Personagem p = c.getelemento(i);
        auxiliar.adicionar(p);
        String trabalho = p.vertrabalho();
        DefaultTableModel val = (DefaultTableModel)tablegrupo.getModel();
        val.addRow(new String[]{p.nomej,p.nomep,Integer.toString(p.levelp),p.classe,p.raça,p.habilidade,Integer.toString(p.levelh),p.especialidade,trabalho});            
    }//GEN-LAST:event_AdicionaGrupoActionPerformed

    private void NoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoiteActionPerformed

    private void Noite1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite1ActionPerformed

    private void Manhã1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã1ActionPerformed

    private void Manhã2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã2ActionPerformed

    private void Manhã3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã3ActionPerformed

    private void Manhã4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã4ActionPerformed

    private void Manhã5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã5ActionPerformed

    private void Manhã6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manhã6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manhã6ActionPerformed

    private void Noite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite2ActionPerformed

    private void Noite3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite3ActionPerformed

    private void Noite4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite4ActionPerformed

    private void Noite5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite5ActionPerformed

    private void Noite6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Noite6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Noite6ActionPerformed

    private void SalvarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarGrupoActionPerformed
        // TODO add your handling code here:
        int tam = tablegrupo.getRowCount();
        String palavra;
        Grupo aux = new Grupo();
        if (tam == 0)
                JOptionPane.showMessageDialog(null, "Grupo vazio!","Erro",JOptionPane.WARNING_MESSAGE);
        else if (tam == 5 || tam == 10 || tam == 25){
                if ((nomegrupo.getText().isEmpty()))
                        JOptionPane.showMessageDialog(null, "Nome inválido","Erro",JOptionPane.WARNING_MESSAGE);
                else{
                        for (int i=0; i<tam;i++)
                                aux.adicionar(auxiliar.getelemento(i));
                        palavra = nomegrupo.getText();
                        DefaultTableModel val = (DefaultTableModel)tablegrupopronto.getModel();
                        val.addRow(new String[]{palavra,Integer.toString(tam)});            
                        c.grupo.add(aux);
                        auxiliar.deletar();
                        DefaultTableModel val2 = (DefaultTableModel)tablegrupo.getModel();
                        val2.setRowCount(0);
                }   
        }
        else
                JOptionPane.showMessageDialog(null, "Número de pessoas inválido (5, 10 ou 15)","Erro",JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_SalvarGrupoActionPerformed

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel val = (DefaultTableModel)table.getModel();
        if (table.getSelectedRow() == -1)
                return;
        c.apagar(table.getSelectedRow());
        auxiliar.remover(table.getSelectedRow());
        ((DefaultTableModel) table.getModel()).removeRow(table.getSelectedRow());
    }//GEN-LAST:event_ApagarActionPerformed

    private void RemovedoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovedoGrupoActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel val = (DefaultTableModel)tablegrupo.getModel();
        int i = tablegrupo.getSelectedRow();
        if (i == -1)
                return;
        ((DefaultTableModel) tablegrupo.getModel()).removeRow(i);
    }//GEN-LAST:event_RemovedoGrupoActionPerformed

    private void limpagrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpagrupoActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel val = (DefaultTableModel)tablegrupo.getModel();
        int j = tablegrupo.getRowCount();
        if (j == -1)
                return;
        for (int i=0;i<j;i++){
                ((DefaultTableModel)tablegrupo.getModel()).removeRow(0); 
                auxiliar.remover(0);
        }
    }//GEN-LAST:event_limpagrupoActionPerformed

    private void excluegrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluegrupoActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel val = (DefaultTableModel)tablegrupopronto.getModel();
        //c.grupo.get(tablegrupopronto.getSelectedRow()).deletar();
        int i = tablegrupopronto.getSelectedRow();
        if (i == -1)
                return;
        c.grupo.remove(i);
        ((DefaultTableModel) tablegrupopronto.getModel()).removeRow(i);
        
    }//GEN-LAST:event_excluegrupoActionPerformed

    private void abregrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abregrupoActionPerformed
        // TODO add your handling code here:
        Personagem p;
        int i = tablegrupopronto.getSelectedRow();
        if (i == -1)
                return;
         DefaultTableModel val = (DefaultTableModel)tablegrupo.getModel();
        for (int j=0; j<c.grupo.get(i).grupo.size();j++){
                    p = c.grupo.get(i).getelemento(j);
                    String trabalho = p.vertrabalho();
                    val.addRow(new String[]{p.nomej,p.nomep,Integer.toString(p.levelp),p.classe,p.raça,p.habilidade,Integer.toString(p.levelh),p.especialidade,trabalho});                       
                    auxiliar.adicionar(p);
        } 
    }//GEN-LAST:event_abregrupoActionPerformed

    private void TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosActionPerformed
        // TODO add your handling code here:
            if (Todos.isSelected()){
                    Manhã.setSelected(true);Manhã1.setSelected(true);Manhã2.setSelected(true);
                    Manhã3.setSelected(true);Manhã4.setSelected(true);Manhã5.setSelected(true);Manhã6.setSelected(true);
                    Tarde.setSelected(true);Tarde1.setSelected(true);Tarde2.setSelected(true);
                    Tarde3.setSelected(true);Tarde4.setSelected(true);Tarde5.setSelected(true);Tarde6.setSelected(true);
                    Noite.setSelected(true);Noite1.setSelected(true);Noite2.setSelected(true);
                    Noite3.setSelected(true);Noite4.setSelected(true);Noite5.setSelected(true);Noite6.setSelected(true);}
            else{
                    Manhã.setSelected(false);Manhã1.setSelected(false);Manhã2.setSelected(false);
                    Manhã3.setSelected(false);Manhã4.setSelected(false);Manhã5.setSelected(false);Manhã6.setSelected(false);
                    Tarde.setSelected(false);Tarde1.setSelected(false);Tarde2.setSelected(false);
                    Tarde3.setSelected(false);Tarde4.setSelected(false);Tarde5.setSelected(false);Tarde6.setSelected(false);
                    Noite.setSelected(false);Noite1.setSelected(false);Noite2.setSelected(false);
                    Noite3.setSelected(false);Noite4.setSelected(false);Noite5.setSelected(false);Noite6.setSelected(false);
            }
    }//GEN-LAST:event_TodosActionPerformed
    
    
    /**
    * @param args the command line arguments
    */
    public void limpar (){
            NomeJogador.setText("");
            NomePersonagem.setText("");
            LevelP.setText("1");
            LevelH.setText("1");
            Raça.setSelectedIndex(0);
            Especialidade.setSelectedIndex(0);
            Habilidade.setSelectedIndex(0);
            Classe.setSelectedIndex(0);
            NomeJogador.requestFocus();
            Manhã.setSelected(false);Manhã1.setSelected(false);Manhã2.setSelected(false);
            Manhã3.setSelected(false);Manhã4.setSelected(false);Manhã5.setSelected(false);Manhã6.setSelected(false);
            Tarde.setSelected(false);Tarde1.setSelected(false);Tarde2.setSelected(false);
            Tarde3.setSelected(false);Tarde4.setSelected(false);Tarde5.setSelected(false);Tarde6.setSelected(false);
            Noite.setSelected(false);Noite1.setSelected(false);Noite2.setSelected(false);
            Noite3.setSelected(false);Noite4.setSelected(false);Noite5.setSelected(false);Noite6.setSelected(false);
    }
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionaGrupo;
    private javax.swing.JButton Apagar;
    private javax.swing.JComboBox Classe;
    private javax.swing.JComboBox Especialidade;
    private javax.swing.JComboBox Habilidade;
    private javax.swing.JFormattedTextField LevelH;
    private javax.swing.JFormattedTextField LevelP;
    private javax.swing.JButton Limpar;
    private javax.swing.JCheckBox Manhã;
    private javax.swing.JCheckBox Manhã1;
    private javax.swing.JCheckBox Manhã2;
    private javax.swing.JCheckBox Manhã3;
    private javax.swing.JCheckBox Manhã4;
    private javax.swing.JCheckBox Manhã5;
    private javax.swing.JCheckBox Manhã6;
    private javax.swing.JCheckBox Noite;
    private javax.swing.JCheckBox Noite1;
    private javax.swing.JCheckBox Noite2;
    private javax.swing.JCheckBox Noite3;
    private javax.swing.JCheckBox Noite4;
    private javax.swing.JCheckBox Noite5;
    private javax.swing.JCheckBox Noite6;
    private javax.swing.JTextField NomeJogador;
    private javax.swing.JTextField NomePersonagem;
    private javax.swing.JComboBox Raça;
    private javax.swing.JButton RemovedoGrupo;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton SalvarGrupo;
    private javax.swing.JCheckBox Tarde;
    private javax.swing.JCheckBox Tarde1;
    private javax.swing.JCheckBox Tarde2;
    private javax.swing.JCheckBox Tarde3;
    private javax.swing.JCheckBox Tarde4;
    private javax.swing.JCheckBox Tarde5;
    private javax.swing.JCheckBox Tarde6;
    private javax.swing.JCheckBox Todos;
    private javax.swing.JButton abregrupo;
    private javax.swing.JButton excluegrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton limpagrupo;
    private javax.swing.JTextField nomegrupo;
    private javax.swing.JTable table;
    private javax.swing.JTable tablegrupo;
    private javax.swing.JTable tablegrupopronto;
    // End of variables declaration//GEN-END:variables

}
